<a href="https://colab.research.google.com/github/Srija616/pyTorchTutorial/blob/main/00_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics of PyTorch and Tensor

This notebook covers basics of tensor - initialization and operations.

# Imports

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Intro to Tensors

Tensors are a way to represent multi-dimensional numeric data. While they may look similar to numpy arrays, they have accelerator support (GPU and TPU)

https://stats.stackexchange.com/questions/355533/tensorflow-why-do-we-need-tensors



In [5]:
# Introduction to tensors - a way to represent multi-dimensional numeric data
# scalar
scalar = torch.tensor(7) # read about tensors
int_num = scalar.item() # get tensor scalar back to Python int
print (f'scalar.type: {scalar.dtype}')
print (f'int_num.type: {type(int_num)}')

vector = torch.tensor([7,7])
vector.ndim  # dimension will be 1. For understanding, it is the number of axes along which we have data or number of pairs of closing brackets
vector.shape # [1,2]
print (f'vector dimensions: {vector.ndim}, vector shape: {vector.shape}')

matrix = torch.tensor([[7,8,3], [9,10, 11]])
matrix.ndim  # 2
matrix.shape # [2,3]
print (f'matrix dimensions: {matrix.ndim}, matrix shape: {matrix.shape}')
tensor = torch.tensor([[[1,2,3], [2,5,6]]])
tensor.ndim  # 3
tensor.shape # [1,2,3]
print (f'tensor dimensions: {tensor.ndim}, tensor shape: {tensor.shape}')

scalar.type: torch.int64
int_num.type: <class 'int'>
vector dimensions: 1, vector shape: torch.Size([2])
matrix dimensions: 2, matrix shape: torch.Size([2, 3])
tensor dimensions: 3, tensor shape: torch.Size([1, 2, 3])


# Random, zero and ones tensor

In [10]:
# Zero and ones tensor
random_tensor = torch.rand(3,4)
zero_tensor = torch.zeros(size = (3,4)) # not necessary to write size, see ones example
target = zero_tensor*random_tensor
ones_tensor = torch.ones((2,3,5))

print (f"random_tensor: {random_tensor}\n")
print (f"zero_tensor: {zero_tensor}\n")
print (f"ones_tensor: {ones_tensor}\n")
print (f"random_tensor value dtype: {random_tensor.dtype}")


random_tensor: tensor([[0.3584, 0.8963, 0.7424, 0.6205],
        [0.3287, 0.0703, 0.8781, 0.6204],
        [0.1799, 0.4073, 0.1027, 0.8446]])

zero_tensor: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

ones_tensor: tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

random_tensor value dtype: torch.float32


# Creating a range of tensors and tensor dtype

In [13]:
# Creating a range of tensors and tensors-like
# twenty = torch.arange(20,40, step =2)
# ten_zeros = torch.zeros_like(input = twenty)

random_val = torch.rand(3,4)
new_tensor = torch.zeros_like(input = random_val)
print (random_val)
print (new_tensor)

tensor([[0.3958, 0.9643, 0.9273, 0.2400],
        [0.5047, 0.8577, 0.1558, 0.9433],
        [0.8920, 0.0778, 0.7412, 0.0556]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
# Tensor Datatypes
float16_tensor = torch.tensor([3.9, 7.9, 7.9], 
                              dtype = torch.float16,
                              device = None,
                              requires_grad = False,
                              )

In [ ]:
float32_tensor = torch.tensor([3.9, 7.9, 7.9],
                              device = None,
                              requires_grad = False,
                              )

In [ ]:
float16_tensor + float32_tensor

tensor([ 7.8004, 15.7984, 15.7984])

To get the right datatype: tensor.dtype

To get the right shape: tensor.shape (shape is an attribute so no ()) or tensor.size() //function or method

To get the right device: tensor.device

Matrix multiplication : torch.matmul(tensor1, tensor 2)
 Element-wise multiplication : tensor * tensor 

 Can't do mean on long dtype (int64), use float32 or float16 or complex dtype 

In [14]:
t = torch.tensor([6,8,9], dtype = torch.float32)
print (t.mean())

# Get the position of the min/max value in a tensor.
print (f'position of max value: {t.argmax()}')
print (f'position of min value: {t.argmin()}')

tensor(7.6667)
position of max value: 2
position of min value: 0


* Reshaping - reshape an input tensor to defined shape

* View - Return view of an input of certain shape but keep the same memory as the original tensor

* Stacking: Concatenates a sequence of tensors along a dimension

* Squeeze - removes all '1' dimensions from a tensor.

* Unsqueeze - Adds '1' dimension to target tensor

* Permute: Return view of the input shape with dimensions permuted in a certain way.

In [17]:
x = torch.arange(1., 11.)
print (x, x.shape)

# Change the view:
xw = x.reshape(10,1)
print ("xw", xw)
xw = xw.squeeze()
print ("xw squeezed: ", xw)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]) torch.Size([10])
xw tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
xw squeezed:  tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


Indexing in PyTorch is similar to indexing in NumPy

In [18]:
x = torch.arange(1,10).reshape(1,3,3)  # We will get 9 values 
print(x, x.shape)
print (x[0][:][1]) # Unable to understand why this is happening

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
tensor([4, 5, 6])


Numpy - scientific Python numerical computing library

In [ ]:
 # numpy-> torch
arr = np.arange(1,8)
x = torch.arange(1,10).reshape(1,3,3)

# Warning -> When converting from numpy to pytorch, pytorch reflects numpy's 
# default datatype i.e. float64. But pytorch default datatype is float32
arr_tensor = torch.from_numpy(arr).type(torch.float32)
print (arr_tensor.dtype, arr_tensor)

# change the value of original array i.e. in Numpy
# The new tensor is in new memory, changing numpy arr doesn't change the tensor
arr = arr+1
print (arr_tensor)

numpy_tensor = arr_tensor.numpy()
print (numpy_tensor, numpy_tensor.dtype) # maintains the dtype you assigned to the tensor

torch.float32 tensor([1., 2., 3., 4., 5., 6., 7.])
tensor([1., 2., 3., 4., 5., 6., 7.])
[1. 2. 3. 4. 5. 6. 7.] float32


In [ ]:
torch.manual_seed(43)
r_t_a = torch.rand(3,5)
torch.manual_seed(43)
r_t_b = torch.rand(3,5)
print (r_t_a)
print ( r_t_b)
print ( r_t_b == r_t_a)

tensor([[0.4540, 0.1965, 0.9210, 0.3462, 0.1481],
        [0.0858, 0.5909, 0.0659, 0.7476, 0.6253],
        [0.9392, 0.1338, 0.5191, 0.5335, 0.5375]])
tensor([[0.4540, 0.1965, 0.9210, 0.3462, 0.1481],
        [0.0858, 0.5909, 0.0659, 0.7476, 0.6253],
        [0.9392, 0.1338, 0.5191, 0.5335, 0.5375]])
tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])
